# Generated by Django 3.1.6 on 2021-02-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20210211_2358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
    ]
